# Site settings
baseurl = "https://crostini.dev"
title = "~/crostini.dev"
paginate = 5
canonifyurls = false
buildFuture = true
theme = "terminal"
googleAnalytics = "UA-136678897-1"
copyright = "crostini.dev Authors"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  author = "crostini.dev staff"
  twitter = "crosdev"
  # set theme to full screen width
  fullWidthTheme = true
  # center theme with default width
  centerTheme = true


  
[languages]
  [languages.en]
    title = "~/crostini.dev"
    subtitle = "Get your Linux On"
    keywords = "crostini,Linux on Chromebook, chromebook,Linux"
    copyright = "&copy; 2019 Crostini.dev authors"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "~/crostini.dev"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "resources"
        name = "Resources"
        url = "/resources"
      [[languages.en.menu.main]]
        identifier = "quick"
        name = "Quick"
        url = "/quick"
[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]